//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTrack
    {
        public int Id { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ComplaintId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Status { get; set; }
        public string ComplaintStatus { get; set; }
    }
}
