//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Staff
    {
        public int Id { get; set; }
        public string USER_PERSON_TYPE { get; set; }
        public string EntityName { get; set; }
        public string LOS { get; set; }
        public string Organisation_SBU { get; set; }
        public string SubSBU { get; set; }
        public string CompetencyName { get; set; }
        public string OfficeLocation { get; set; }
        public string office { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Mobile_no { get; set; }
        public string People_Manager_ID { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Date_Of_Birth { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
    }
}
