//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMasters_History
    {
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeId { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string WorkEmail { get; set; }
        public string TimeType { get; set; }
        public int BusinessTitle { get; set; }
        public int Company { get; set; }
        public int LOSId { get; set; }
        public int SBUId { get; set; }
        public int SubSBUId { get; set; }
        public int CompentencyId { get; set; }
        public int LocationId { get; set; }
        public int RegionId { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public string MobileNo { get; set; }
        public string Manager { get; set; }
        public string Type { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ImagePath { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public string EntityState { get; set; }
        public int UserMasterId { get; set; }
    }
}
